/**
 * Patient-facing "bottom line" executive summaries, transcribed from the
 * physician deep-research Patient Education Briefs (physician-review pending).
 * Merged onto each condition by conditions/index.ts (keyed by condition id).
 */
export const executiveSummaries: Record<string, string> = {
  'achilles-tendinopathy': `Midportion Achilles tendinopathy is usually a load-related tendon problem, not a tear that must be shut down. The best-supported treatment is progressive calf loading — starting at a tolerable level and building toward single-leg strength and spring-like work. Most people improve over 6 to 12 weeks, but a fuller return to running and jumping often takes 3 to 6 months, and stubborn cases can take longer.`,
  'patellofemoral-pain': `Patellofemoral pain is a load-related pain condition around or behind the kneecap. The best-supported treatment is exercise therapy plus education, often emphasizing knee-targeted and hip-targeted strengthening. Many people improve in 6 to 12 weeks, but symptoms can persist or recur if training errors, strength deficits, or fear of movement are not addressed.`,
  'rotator-cuff-tendinopathy': `Rotator cuff–related shoulder pain usually responds best to education plus progressive exercise, not imaging-driven fear. Most patients improve over 6 to 12 weeks, though full recovery may take 3 to 6 months.`,
  'frozen-shoulder': `Frozen shoulder causes pain plus true stiffness of the shoulder capsule. It usually improves, but often slowly, over 6 to 18 months, and occasionally longer.`,
  'ac-joint-sprain': `An AC sprain is an injury where the collarbone and top of the shoulder are jarred apart. Grade I to II injuries usually recover with nonoperative care in 2 to 8 weeks; grade III and above take longer and are more controversial.`,
  'biceps-tendinopathy': `Long-head biceps tendinopathy is front-of-shoulder pain from the long head of the biceps tendon or tendon sheath. Recovery commonly takes 6 to 12 weeks, but chronic cases may last 3 to 6 months. Evidence for conservative care is thinner than for cuff pain.`,
  'tennis-elbow': `Tennis elbow is a load-related tendinopathy at the common extensor tendon, usually near the extensor carpi radialis brevis origin. Most cases improve with time plus loading, often over 6 to 12 weeks, but chronic cases can take 6 to 12 months.`,
  'golfers-elbow': `Golfer's elbow is a tendinopathy at the common flexor-pronator origin on the inner elbow. Many improve with load management and strengthening, though progress is measured in months and recovery often takes 2 to 6 months.`,
  'cubital-tunnel-syndrome': `Cubital tunnel syndrome is compression or irritation of the ulnar nerve at the elbow. Mild cases often improve with activity modification and night splinting over 6 to 12 weeks.`,
  'de-quervain-tenosynovitis': `De Quervain's causes pain at the thumb side of the wrist from the first dorsal extensor compartment tendon sheath, which houses the abductor pollicis longus and extensor pollicis brevis. Many patients improve over 2 to 8 weeks with splinting and/or injection.`,
  'wrist-sprain-tfcc': `A TFCC sprain causes ulnar-sided wrist pain from the triangular fibrocartilage complex, a key stabilizer near the distal ulna. Many sprains improve with immobilization and rehab over 6 to 12 weeks.`,
  'trigger-finger': `Trigger finger is stenosing tenosynovitis where the flexor tendon catches at the A1 pulley. Many patients improve with injection; locked or recurrent cases may need procedural release.`,
  'mechanical-neck-pain': `Mechanical neck pain is pain from the cervical spine, muscles, and related soft tissues without major nerve-root findings. Most episodes improve over 2 to 6 weeks, though recurrence is common.`,
  'cervical-radiculopathy': `Cervical radiculopathy is irritation of a cervical nerve root, causing neck pain plus arm pain, numbness, or tingling. Many cases improve over 6 to 12 weeks without surgery.`,
  'low-back-pain': `Non-specific low back pain means back pain without a dangerous cause or a clear major nerve-root syndrome. Many acute episodes improve in 2 to 6 weeks, but recurrence is common.`,
  'lumbar-radiculopathy': `Lumbar radiculopathy is irritation of a lumbar nerve root, causing back pain with leg pain, numbness, or weakness. Many cases improve over 6 to 12 weeks.`,
  spondylolysis: `Spondylolysis is a stress injury of the pars interarticularis, most often in young athletes. Many improve with time, activity modification, and rehab over 6 to 12 weeks, with return to sport often 3 to 6 months.`,
  'gluteal-tendinopathy': `Gluteal tendinopathy is lateral hip pain from the gluteus medius/minimus tendons, often grouped under GTPS. Best evidence supports education plus exercise. Recovery often takes 8 to 12 weeks for meaningful gains and 3 to 6 months in stubborn cases.`,
  'hip-osteoarthritis': `Hip OA is degeneration of the hip joint cartilage, subchondral bone, synovium, and periarticular tissues. Exercise, education, and weight management are core treatments. OA is long-term, but symptoms often improve meaningfully with conservative care.`,
  'proximal-hamstring-tendinopathy': `Proximal hamstring tendinopathy causes deep buttock pain from the proximal hamstring tendon origin at the ischial tuberosity. Recovery is often slower than patients expect, commonly 3 to 6 months or more.`,
  'femoroacetabular-impingement': `FAI is hip pain related to abnormal contact between the femoral head-neck junction and the acetabular rim, often with labral involvement. Initial management usually emphasizes education and exercise; symptom improvement often takes 6 to 12 weeks or longer.`,
  'patellar-tendinopathy': `Patellar tendinopathy is a load-related tendon problem at the patellar tendon, usually the inferior-pole origin. It often needs 3 to 6 months or more of loading rehab.`,
  'knee-osteoarthritis': `Knee OA is degeneration of the entire knee joint organ, not just cartilage. Exercise, weight management, and selected analgesic strategies are central. OA is chronic, but symptoms often improve with conservative care.`,
  'mcl-sprain': `An MCL sprain is an injury to the medial collateral ligament on the inside of the knee. Grade I injuries often recover in 2 to 6 weeks, grade II in 4 to 8 weeks, and grade III takes longer, is more individualized, and may need specialist review.`,
  'it-band-syndrome': `IT band syndrome is lateral knee pain related to the iliotibial band compression/friction region near the lateral femoral epicondyle. It commonly improves in 4 to 8 weeks with training modification and rehab, though chronic cases last longer.`,
  'medial-tibial-stress-syndrome': `MTSS causes exercise-related pain along the inner shin from tibial periosteal and bone-stress-related overload. Recovery commonly takes 4 to 12 weeks, longer if symptoms are ignored.`,
  'lateral-ankle-sprain': `A lateral ankle sprain usually injures the anterior talofibular ligament, sometimes the calcaneofibular ligament. Most low-grade sprains improve in 1 to 6 weeks, but instability can persist if rehab is too brief.`,
  'plantar-heel-pain': `Plantar heel pain usually involves the plantar fascia and related heel tissues — often called plantar fasciitis, although degenerative features are common. Recovery often starts within 6 to 12 weeks but may take 3 to 12 months.`,
}
