/**
 * String-key -> lucide icon map. Content files reference icons by key so they
 * don't all import lucide directly, and so content stays easy to serialize.
 */
import {
  Activity,
  AlertTriangle,
  ArrowRight,
  Bandage,
  Bone,
  BookOpen,
  Brain,
  Check,
  ChevronRight,
  CircleDot,
  CircleHelp,
  ClipboardList,
  Dumbbell,
  ExternalLink,
  FileText,
  Footprints,
  Gauge,
  Hand,
  HeartPulse,
  Home,
  Info,
  Layers,
  ListPlus,
  Microscope,
  Move,
  Orbit,
  Play,
  Plus,
  Printer,
  Search,
  ShieldAlert,
  ShieldCheck,
  Spline,
  Stethoscope,
  Syringe,
  Target,
  UserRound,
  Waves,
  X,
} from 'lucide-react'
import type { IconComponent } from './types'

export const icons: Record<string, IconComponent> = {
  // regions (non-figurative glyphs — no human/stick figures)
  shoulder: CircleDot,
  elbow: Move,
  'wrist-hand': Hand,
  neck: Brain,
  'low-back': Spline,
  'hip-pelvis': Orbit,
  knee: Bone,
  'lower-leg': Activity,
  'ankle-foot': Footprints,
  // sports / generic
  running: Activity,
  pickleball: Target,
  tennis: Target,
  golf: Target,
  basketball: Dumbbell,
  volleyball: Activity,
  soccer: Activity,
  cycling: Activity,
  swimming: Waves,
  lifting: Dumbbell,
  climbing: Activity,
  throwing: Activity,
  general: Activity,
  // procedures
  'ultrasound-guided': Microscope,
  prp: CircleDot,
  'hyaluronic-acid': Syringe,
  shockwave: Waves,
  tenotomy: Bandage,
  corticosteroid: Syringe,
  // nav / ui
  dashboard: Gauge,
  regions: Layers,
  conditions: BookOpen,
  exercises: Dumbbell,
  procedures: Syringe,
  evidence: Bone,
  program: ClipboardList,
  ultrasound: Microscope,
  stethoscope: Stethoscope,
  home: Home,
  print: Printer,
  add: ListPlus,
  play: Play,
  external: ExternalLink,
  help: CircleHelp,
  shield: ShieldCheck,
  alert: ShieldAlert,
  warning: AlertTriangle,
  info: Info,
  arrowRight: ArrowRight,
  chevronRight: ChevronRight,
  check: Check,
  plus: Plus,
  search: Search,
  file: FileText,
  user: UserRound,
  heart: HeartPulse,
  close: X,
}

export function getIcon(key: string | undefined): IconComponent {
  return (key && icons[key]) || Info
}
